import { Injectable } from '@angular/core';
import { Title } from '@angular/platform-browser';
import { InMemoryDbService } from 'angular-in-memory-web-api';
import { Movie } from './movie';
import { Vam } from './vam';

@Injectable({
  providedIn: 'root',
})
export class InMemoryDataService implements InMemoryDbService {
  createDb() {
    let movies = [
      {
        id: 1,
        studio: 'Orion',
        name: 'Robocop',
        territory: 'EN-US',
        streetdate: 'October 2022',
        status: 'In Progress',
        vamid: 1,
        vam: [
          {
            vamid: 1,
            id: 1,
            name: 'Inspiration for Robocop',
            group: 'Making Of',
            type: 'Video',
            language: 'English',
            source: 'Received',
            titlecard: 'xxxx',
            legalcard: 'xxxx',
            deliverable: 'Pending',
            proxy: 'Pending',
            itt: 'Pending',
            thumbnail: 'Received',
            status: 'In Progress',
          },
          {
            vamid: 2,
            id: 2,
            name: 'Director Commentary',
            group: 'Audio Comm.',
            type: 'Audio',
            language: 'English',
            source: 'Received',
            titlecard: 'No',
            legalcard: 'No',
            deliverable: 'QA Failed',
            proxy: 'Pending',
            itt: 'Pending',
            thumbnail: 'Pending',
            status: 'In Progress',
          },
          {
            vamid: 3,
            id: 3,
            name: 'Robo & Lois Make-out',
            group: 'Deleted Scenes',
            type: 'Video',
            language: 'English',
            source: 'Received',
            titlecard: 'No',
            legalcard: 'No',
            deliverable: 'Complete',
            proxy: 'Complete',
            itt: 'In QA',
            thumbnail: 'Received',
            status: 'In Progress',
          },
          {
            vamid: 4,
            id: 4,
            name: 'Peter Weller',
            group: 'Gallery',
            type: 'Image',
            language: '-',
            source: '-',
            titlecard: '',
            legalcard: '',
            deliverable: 'Received',
            proxy: '-',
            itt: '-',
            thumbnail: '-',
            status: 'Complete',
          },
        ],
        milestones: [
          {
            id: 2,
            sku: 'ENG',
            qavendor: 'TestTronic',
            qastatus: 'pending',
            portal: 'iTunes',
            portalstatus: 'pending',
            release: '5/8/2022',
            releasestatus: 'pending',
          },
        ],
      },
      {
        id: 2,
        studio: 'MGM',
        name: 'James Bond',
        territory: 'RUS',
        streetdate: 'August 2022',
        status: 'In Progress',
        vamid: 2,
        vam: [
          {
            vamid: 1,
            id: 1,
            name: 'James Vam',
            language: 'xxxx',
            source: 'bonus-reel.prores',
            titlecard: 'xxxx',
            legalcard: 'xxxx',
            deliverable: 'xxxx',
            proxy: 'xxxx',
            itt: 'xxxx',
            thumbnail: 'xxxx',
            status: 'xxxx',
          },
        ],
        milestones: [
          {
            id: 1,
            sku: 'ENG',
            qavendor: 'BluFocus',
            qastatus: 'pending',
            portal: 'iTunes',
            portalstatus: 'pending',
            release: '5/8/2022',
            releasestatus: 'pending',
          },
        ],
      },
      {
        id: 3,
        studio: 'Warner Bros.',
        name: 'Batman',
        territory: 'BRA',
        streetdate: 'January 2022',
        status: 'Complete',
        vamid: 3,
        vam: [
          {
            vamid: 1,
            id: 1,
            name: 'BatVam',
            language: 'xxxx',
            source: 'bonus-reel.prores',
            titlecard: 'xxxx',
            legalcard: 'xxxx',
            deliverable: 'xxxx',
            proxy: 'xxxx',
            itt: 'xxxx',
            thumbnail: 'xxxx',
            status: 'xxxx',
          },
        ],
      },
      {
        id: 4,
        studio: 'Orion',
        name: 'Conan',
        territory: 'EN-UK',
        streetdate: 'February 2022',
        status: 'Pending',
        vamid: 4,
        vam: [
          {
            vamid: 1,
            id: 1,
            name: 'ConoVam',
            language: 'xxxx',
            source: 'bonus-reel.prores',
            titlecard: 'xxxx',
            legalcard: 'xxxx',
            deliverable: 'xxxx',
            proxy: 'xxxx',
            itt: 'xxxx',
            thumbnail: 'xxxx',
            status: 'xxxx',
          },
        ],
      },
      {
        id: 5,
        studio: 'Universal Studios',
        name: 'Back to The Future',
        territory: 'EN-US',
        streetdate: 'February 2022',
        status: 'Complete',
        vamid: 5,
        vam: [
          {
            vamid: 1,
            id: 1,
            name: 'Back to the Vam',
            language: 'xxxx',
            source: 'bonus-reel.prores',
            titlecard: 'xxxx',
            legalcard: 'xxxx',
            deliverable: 'xxxx',
            proxy: 'xxxx',
            itt: 'xxxx',
            thumbnail: 'xxxx',
            status: 'xxxx',
          },
        ],
      },
      {
        id: 6,
        studio: '20th Century Fox',
        name: 'Victor Frankenstein',
        territory: 'EN-US',
        streetdate: 'February 2022',
        status: 'Complete',
        vamid: 5,
        vam: [
          {
            vamid: 1,
            id: 1,
            group: 'Deleted Scenes',
            name: 'Lorelie Gives a Book',
            type: 'Video',
            language: 'ENH',
            source: 'A2309607.mov',
            titlecard: 'Yes',
            legalcard: 'Yes',
            deliverable: '7344718.mov',
            proxy: '7220039.mov',
            itt: '7220039.itt',
            thumbnail: 'Yes',
            status: 'In Production',
          },
          {
            vamid: 1,
            id: 2,
            group: 'Deleted Scenes',
            name: 'Turpin Questions Barnaby',
            type: 'Video',
            language: 'ENH',
            source: 'A2309607.mov',
            titlecard: 'Yes',
            legalcard: 'Yes',
            deliverable: '7344718.mov',
            proxy: '7220039.mov',
            itt: '7220039.itt',
            thumbnail: 'Yes',
            status: 'In Production',
          },
          {
            vamid: 1,
            id: 3,
            group: 'Deleted Scenes',
            name: 'Play All',
            type: 'Video',
            language: 'ENH',
            source: 'A2309607.mov',
            titlecard: 'Yes',
            legalcard: 'Yes',
            deliverable: '7344718.mov',
            proxy: '7220039.mov',
            itt: '7220039.itt',
            thumbnail: 'Yes',
            status: 'In Production',
          },
          {
            vamid: 1,
            id: 3,
            group: 'Making Of',
            name: 'Directing Frankenstein',
            type: 'Video',
            language: 'ENH',
            source: 'A2309607.mov',
            titlecard: 'Yes',
            legalcard: 'Yes',
            deliverable: '7344718.mov',
            proxy: '7220039.mov',
            itt: '7220039.itt',
            thumbnail: 'Yes',
            status: 'In Production',
          },
          {
            vamid: 1,
            id: 3,
            group: 'Making Of',
            name: 'Becoming Victor',
            type: 'Video',
            language: 'ENH',
            source: 'A2309607.mov',
            titlecard: 'Yes',
            legalcard: 'Yes',
            deliverable: '7344718.mov',
            proxy: '7220039.mov',
            itt: '7220039.itt',
            thumbnail: 'Yes',
            status: 'In Production',
          },
          {
            vamid: 1,
            id: 3,
            group: 'Making Of',
            name: 'Play All',
            type: 'Video',
            language: 'ENH',
            source: 'A2309607.mov',
            titlecard: 'Yes',
            legalcard: 'Yes',
            deliverable: '7344718.mov',
            proxy: '7220039.mov',
            itt: '7220039.itt',
            thumbnail: 'Yes',
            status: 'In Production',
          },
          {
            vamid: 1,
            id: 3,
            group: 'Gallery',
            name: 'Production Design',
            type: 'Image',
            language: 'ENH',
            source: 'A2309607.mov',
            titlecard: 'Yes',
            legalcard: 'Yes',
            deliverable: '7344718.mov',
            proxy: '7220039.mov',
            itt: '7220039.itt',
            thumbnail: 'Yes',
            status: 'In Production',
          },
          {
            vamid: 1,
            id: 3,
            group: 'Gallery',
            name: 'Production Photography',
            type: 'Image',
            language: 'ENH',
            source: 'A2309607.mov',
            titlecard: 'Yes',
            legalcard: 'Yes',
            deliverable: '7344718.mov',
            proxy: '7220039.mov',
            itt: '7220039.itt',
            thumbnail: 'Yes',
            status: 'In Production',
          },
          {
            vamid: 1,
            id: 3,
            group: 'Gallery',
            name: 'Behind-the-Scenes',
            type: 'Image',
            language: 'ENH',
            source: 'A2309607.mov',
            titlecard: 'Yes',
            legalcard: 'Yes',
            deliverable: '7344718.mov',
            proxy: '7220039.mov',
            itt: '7220039.itt',
            thumbnail: 'Yes',
            status: 'In Production',
          },
          {
            vamid: 1,
            id: 3,
            group: '',
            name: 'Theatrical Trailer',
            type: 'Video',
            language: 'ENH',
            source: 'A2309607.mov',
            titlecard: 'Yes',
            legalcard: 'Yes',
            deliverable: '7344718.mov',
            proxy: '7220039.mov',
            itt: '7220039.itt',
            thumbnail: 'Yes',
            status: 'In Production',
          },
        ],
      },
    ];

    return { movies };
  }

  // Overrides the genId method to ensure that a hero always has an id.
  // If the heroes array is empty,
  // the method below returns the initial number (11).
  // if the heroes array is not empty, the method below returns the highest
  // hero id + 1.
  genId(movies: Movie[]): number {
    return movies.length > 0
      ? Math.max(...movies.map((movie) => movie.id)) + 1
      : 11;
  }
  constructor() {}
}
